name: Slack-Notifier
on:
  workflow_run:
    workflows: ["*"]
    types: [completed]
    branches: [main]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: network-log
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/8115255?s=200&v=4
          SLACK_MESSAGE: More details on ${{ github.event.workflow_run.html_url }}
          SLACK_TITLE: The workflow ${{ github.event.workflow.name }} run failed
          SLACK_USERNAME: Network-Monorepo-GitAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MSG_AUTHOR: ${{ github.event.workflow_run.workflow_url.head_commit.committer.name }}
