name: test setup

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      command:
        required: false
        type: string
        default: npm run test
      docker-services:
        required: false
        type: string
      run-brokers-and-trackers:
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: build (cached)
        uses: ./.github/workflows/reusable/cached-build
      - name: start docker services
        if: ${{ inputs.docker-services != '' }}
        uses: streamr-dev/streamr-docker-dev-action@v1.0.1
        with:
          services-to-start: ${{ inputs.docker-services }}
      - name: run brokers and trackers
        if: ${{ inputs.run-brokers-and-trackers }}
        uses: ./.github/workflows/reusable/run-brokers-and-trackers
      - name: test
        working-directory: 'packages/${{ inputs.package }}'
        run: ${{ inputs.command }}
      - name: upload logs
        if: ${{ inputs.docker-services != '' || inputs.run-brokers-and-trackers }}
        uses: ./.github/workflows/reusable/collect-and-upload-logs
        with:
          artifact_prefix: ${{ inputs.package }}
